/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellRolesIndexRouteImport } from './routes/_shell.roles.index'
import { Route as ShellRolesRoleIdRouteImport } from './routes/_shell.roles.$roleId'
import { Route as ShellUsersIndexRouteImport } from './routes/_shell.users.index'
import { Route as ShellUsersUserIdRouteImport } from './routes/_shell.users.$userId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRolesIndexRoute = ShellRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRolesRoleIdRoute = ShellRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersIndexRoute = ShellUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersUserIdRoute = ShellUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/roles/$roleId': typeof ShellRolesRoleIdRoute
  '/users/$userId': typeof ShellUsersUserIdRoute
  '/roles/': typeof ShellRolesIndexRoute
  '/users/': typeof ShellUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/roles/$roleId': typeof ShellRolesRoleIdRoute
  '/users/$userId': typeof ShellUsersUserIdRoute
  '/roles': typeof ShellRolesIndexRoute
  '/users': typeof ShellUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/roles/$roleId': typeof ShellRolesRoleIdRoute
  '/_shell/users/$userId': typeof ShellUsersUserIdRoute
  '/_shell/roles/': typeof ShellRolesIndexRoute
  '/_shell/users/': typeof ShellUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/roles/$roleId' | '/users/$userId' | '/roles/' | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/roles/$roleId' | '/users/$userId' | '/roles' | '/users'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/roles/$roleId'
    | '/_shell/users/$userId'
    | '/_shell/roles/'
    | '/_shell/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/roles/': {
      id: '/_shell/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof ShellRolesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/roles/$roleId': {
      id: '/_shell/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof ShellRolesRoleIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users/': {
      id: '/_shell/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ShellUsersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users/$userId': {
      id: '/_shell/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof ShellUsersUserIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellRolesRoleIdRoute: typeof ShellRolesRoleIdRoute
  ShellUsersUserIdRoute: typeof ShellUsersUserIdRoute
  ShellRolesIndexRoute: typeof ShellRolesIndexRoute
  ShellUsersIndexRoute: typeof ShellUsersIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellRolesRoleIdRoute: ShellRolesRoleIdRoute,
  ShellUsersUserIdRoute: ShellUsersUserIdRoute,
  ShellRolesIndexRoute: ShellRolesIndexRoute,
  ShellUsersIndexRoute: ShellUsersIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
